add cart and item model and other related classes
Bohadan-Markatov/bookshop-spring-project pull request #11
Opened 2024-05-21 22:00 UTC by Bohadan-Markatov

2024-05-22 09:40 UTC, AnyaRatusnyak approved these changes
Looks good))

2024-05-23 10:16 UTC, yevheniisynytsia requested changes
Well done! Left some minor comments

2024-05-23 10:16 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/controller/ShoppingCartController.java
> +    ) {
```suggestion
            @RequestBody @Valid CartItemCreateDto cartItemCreateDto) {

```

2024-05-23 10:16 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/mapper/ShoppingChartMapper.java
> +    @Mapping(target = "userId", expression = "java(shoppingCart.getUser().getId())")
```suggestion
    @Mapping(target = "userId", source = "user.id")
```
isn't it working?

2024-05-23 10:16 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/repository/ShoppingCartRepository.java
> +    ShoppingCart findByUserId(Long userId);
should be `Opional<ShoppingCart>`

2024-05-23 10:16 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
what if it is null?

2024-05-24 10:09 UTC, yevheniisynytsia approved these changes
🔥

2024-05-24 20:58 UTC, merged